# Generated by Django 4.1.3 on 2022-11-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Simulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_size",
                    models.DecimalField(decimal_places=2, default=1000, max_digits=20),
                ),
                ("total_trades", models.IntegerField(default=100)),
                (
                    "risk_per_trade",
                    models.DecimalField(decimal_places=2, default=2, max_digits=4),
                ),
                (
                    "win_rate",
                    models.DecimalField(decimal_places=2, default=70, max_digits=4),
                ),
                (
                    "risk_reward",
                    models.DecimalField(decimal_places=4, default=2, max_digits=4),
                ),
            ],
        ),
    ]
